In [2]:
# imports
import librosa
import os
import glob
import wave
import numpy as np
from numpy import array
from numpy import asarray
from numpy import zeros
import matplotlib.pyplot as plt
import librosa.display
from pathlib import Path
import keras
import cv2
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers.convolutional import Convolution1D, Convolution2D, MaxPooling2D, Conv2DTranspose
from keras.layers import Dense, Bidirectional, LSTM
from keras.layers import Flatten
from keras.layers import Embedding
from keras.layers import Reshape
from keras.layers import UpSampling2D, UpSampling1D
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from keras.layers.core import Flatten, Dense, Activation
from keras.utils import np_utils
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Dense
from keras.layers import AveragePooling2D

In [3]:
# Connecting to google drive storage
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [4]:
  # paths
path = "/content/gdrive/My Drive/Dataset/Test/wavs"
spectrogram_path = "/content/gdrive/My Drive/Dataset/Test/Spectrogram/"
Mel_spectrogram_path = "/content/gdrive/My Drive/Dataset/Test/Mel-Spectrogram/"
text_path = '/content/gdrive/My Drive/Dataset/Test/metadata.csv'

# files = os.listdir(path)

In [ ]:
# # Storing linear Spectrogram

# for filename in glob.glob(os.path.join(path, '*.wav')):

#     y, sr = librosa.load(filename)

#     window_size = 1024
#     window = np.hanning(window_size)
#     stft  = librosa.core.spectrum.stft(y, n_fft=window_size, hop_length=512, window=window)
#     out = 2 * np.abs(stft) / np.sum(window)

#     name = spectrogram_path + Path(filename).stem
      
#     fig = plt.Figure()
#     canvas = FigureCanvas(fig)
#     ax = fig.add_subplot(111)
#     p = librosa.display.specshow(librosa.amplitude_to_db(out, ref=np.max), ax=ax, y_axis='hz', x_axis='time')
#     fig.savefig(name + '.png')

In [10]:
# # Storing mel spectrogram
# orig = []
# i = 0
# for filename in glob.glob(os.path.join(path, '*.wav')):
#   scale, sr = librosa.load(filename)
#   mel_spectrogram = librosa.feature.melspectrogram(scale, sr = sr, n_fft = 2048, hop_length = 512, n_mels = 128)
#   # print(mel_spectrogram.shape)
#   # print(mel_spectrogram)
#   # log_mel_spectrogram = librosa.power_to_db(mel_spectrogram)
#   # print(log_mel_spectrogram.shape)
#   # print(type(log_mel_spectrogram))
#   # print(mel_spectrogram)
#   # crop = cv2.resize(mel_spectrogram,(256, 80))
#   # print(crop.shape)
#   # print(crop)
#   orig.append(mel_spectrogram)
#   i += 1 

# import pickle

# print(len(orig))
# # orig = np.array(orig)
# # print(orig.shape)
# # name = new_path + Path(filename).stem
# new_file = "/content/gdrive/My Drive/Dataset/Test/mel_test_full.pkl"
# with open(new_file, 'wb') as fp:
#   pickle.dump(orig, fp)

# ret = []
# with open(new_file, 'rb') as fp:
#   ret = pickle.load(fp)
# print(len(ret))

13109
13109


In [18]:
orig = []
i = 0
for filename in glob.glob(os.path.join(path, '*.wav')):
  scale, sr = librosa.load(filename)
  print(scale.shape[0], sr)
  mel_spectrogram = librosa.feature.melspectrogram(scale, sr = sr, n_fft = 2048, hop_length = int(scale.shape[0] / 255), n_mels = 128)
  print(mel_spectrogram.shape)
  # print(mel_spectrogram)
  # log_mel_spectrogram = librosa.power_to_db(mel_spectrogram)
  # print(log_mel_spectrogram.shape)
  # print(type(log_mel_spectrogram))
  # print(mel_spectrogram)
  # crop = cv2.resize(mel_spectrogram,(256, 80))
  # print(crop.shape)
  # print(crop)
  orig.append(mel_spectrogram)
  i += 1 
  if(i > 5):
    break

125597 22050
(128, 256)
186013 22050
(128, 256)
134813 22050
(128, 256)
171933 22050
(128, 256)
136861 22050
(128, 256)
150173 22050
(128, 256)


In [13]:
import librosa
import librosa.display
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import IPython.display as ipd

def read_audio_from_filename(filename):
    audio, sr = librosa.load(filename)
    print(audio.shape, int(audio.shape[0]/256))
    # D = np.abs(librosa.stft(audio))**2
    mel_spectrogram = librosa.feature.melspectrogram(y=audio, sr=sr, n_fft = 2048, hop_length = int(audio.shape[0]/256), n_mels = 128)
    # crop = cv2.resize(mel_spectrogram,(256, 128))
    return mel_spectrogram
def convert_data():
    wav_filename = "/content/gdrive/My Drive/Dataset/Test/wavs/LJ001-0001.wav"
    audio = read_audio_from_filename(wav_filename)
    print(audio.shape, type(audio))
    return audio
specto = convert_data()
print('sd')
res = librosa.feature.inverse.mel_to_audio(specto)
print(res.shape, type(res)) 
import soundfile as sf
sf.write("/content/gdrive/My Drive/Dataset/Test/hop_file1.wav", res, 22050)
res1 = librosa.feature.inverse.mel_to_audio(specto, hop_length=831)
sf.write("/content/gdrive/My Drive/Dataset/Test/hop_file2.wav", res1, 22050)


(212893,) 831
(128, 257) <class 'numpy.ndarray'>
sd
(131072,) <class 'numpy.ndarray'>


In [14]:
import IPython.display as ipd
# generated
ipd.Audio("/content/gdrive/My Drive/Dataset/Test/stereo_file6.wav")

In [15]:
ipd.Audio("/content/gdrive/My Drive/Dataset/Test/hop_file1.wav")

In [16]:
ipd.Audio("/content/gdrive/My Drive/Dataset/Test/hop_file2.wav")

In [ ]:
# original
ipd.Audio("/content/gdrive/My Drive/Dataset/Test/wavs/LJ001-0001.wav")

In [ ]:
# test-check cell
import cv2
from PIL import Image

# temp = Image.open('/content/gdrive/My Drive/Dataset/Test/Mel-Spectrogram/LJ001-0004.png')
# print(np.array(temp).shape)
# temp = Image.open('/content/gdrive/My Drive/Dataset/Test/Mel-Spectrogram/LJ001-0012.png')
# print(np.array(temp).shape)
# temp = Image.open('/content/gdrive/My Drive/Dataset/Test/Mel-Spectrogram/LJ001-0047.png')
# print(np.array(temp).shape)


# t = Tokenizer()
# t.fit_on_texts(docs) 
# vocab_size = len(t.word_index) + 1
# print('vocab size ', vocab_size)
# print(t.word_index)

# embeddings_index = {}
# f = open('/content/gdrive/My Drive/Dataset/Test/Glove/glove.6B.100d.txt')
# i = 0
# for line in f:
#   values = line.split()
#   word = values[0]
#   coefs = asarray(values[1:], dtype = 'float32')
#   print(coefs.shape)
#   embeddings_index[word] = coefs
#   i += 1
#   print(values)
#   print(embeddings_index)
#   if(i > 2):
#     break
# f.close()
# print('Loaded %s word vectors.' % len(embeddings_index))

# # create a weight matrix for words in training docs
# embedding_matrix = zeros((vocab_size, 256))
# for word, i in t.word_index.items():
# 	embedding_vector = embeddings_index.get(word)
# print(embedding_vector)

NameError: ignored

In [ ]:
# Dataset metadata processing
max_length = 0
docs = []
index = 0

with open(text_path, encoding = 'utf-8') as fp:
  for line in fp:
    parts = line.strip().split('|')
    max_length = max(max_length, len(parts[2]))
    docs.append(parts[2])
    index += 1

print('maximum length of charcters in a sentence of training data is', max_length)
print('total length ', index)
print(docs[:5])

maximum length of charcters in a sentence of training data is 187
total length  13100
['Printing, in the only sense with which we are at present concerned, differs from most if not from all the arts and crafts represented in the Exhibition', 'in being comparatively modern.', 'For although the Chinese took impressions from wood blocks engraved in relief for centuries before the woodcutters of the Netherlands, by a similar process', 'produced the block books, which were the immediate predecessors of the true printed book,', 'the invention of movable metal letters in the middle of the fifteenth century may justly be considered as the invention of the art of printing.']


In [ ]:
# Model Development
# part-1

# preparing tokenizer
t = Tokenizer()
t.fit_on_texts(docs) 
vocab_size = len(t.word_index) + 1
print('vocab size ', vocab_size)

encoded_docs = t.texts_to_sequences(docs)
print('encoded docs: ', encoded_docs)

# padding the documents to a max words containing sentence
padded_docs = pad_sequences(encoded_docs, maxlen = max_length, padding = 'post')
# padded_docs = docs
print('padded docs: ', padded_docs)

# loading the whole embedding into memory
embeddings_index = dict()
f = open('/content/gdrive/My Drive/Dataset/Test/Glove/glove.6B.100d.txt')
for line in f:
	values = line.split()
	word = values[0]
	coefs = asarray(values[1:], dtype = 'float32')
	embeddings_index[word] = coefs
f.close()
print('Loaded %s word vectors.' % len(embeddings_index))

# create a weight matrix for words in training docs
embedding_matrix = zeros((vocab_size, 100))
for word, i in t.word_index.items():
  embedding_vector = embeddings_index.get(word)
  if embedding_vector is not None:
    embedding_matrix[i] = embedding_vector


vocab size  14136
encoded docs:  [[984, 5, 1, 66, 1513, 15, 20, 127, 52, 18, 268, 718, 8562, 24, 96, 100, 22, 24, 39, 1, 5160, 3, 6408, 2333, 5, 1, 3331], [5, 188, 5161, 658], [12, 169, 1, 8563, 203, 3332, 24, 2997, 1372, 4336, 5, 985, 12, 2522, 80, 1, 8564, 2, 1, 8565, 16, 6, 570, 1068], [1113, 1, 947, 659, 20, 19, 1, 823, 6409, 2, 1, 986, 909, 367], [1, 5162, 2, 3333, 2019, 504, 5, 1, 741, 2, 1, 3334, 874, 120, 5163, 21, 401, 14, 1, 5162, 2, 1, 1685, 2, 984], [3, 17, 27, 719, 1587, 5, 987, 8, 14, 33, 948, 2, 1373, 5164], [1, 2523, 367, 909, 15, 3333, 1767, 1, 6410, 28, 221, 36, 742, 3335, 2, 62, 556, 200, 67], [73, 181, 32, 6411], [984, 106, 12, 183, 420, 120, 21, 401, 14, 1, 1685, 2, 475, 659, 16, 313, 2, 3333, 1767], [133, 14, 39, 659, 22, 2524, 743, 14, 571, 659, 4337, 2334, 2, 1767, 2758, 4, 383, 8566], [17, 27, 2, 1, 70, 1316, 8, 1, 402, 207, 92, 21, 1373, 5, 383], [744, 14, 44, 51, 47, 27, 676, 28, 1374, 5165, 5, 6412, 2998, 28, 984, 1686, 504], [86, 5, 1, 107, 1249, 15, 2999, 

In [ ]:
output = np.load('/content/gdrive/My Drive/Dataset/Test/Mel-Numpy/mel.npy')[:2016]
print(output.shape)
inp = padded_docs[:2016]
print(inp.shape)
print(padded_docs[:2043])

(2016, 128, 128, 3)
(2016, 187)
[[ 984    5    1 ...    0    0    0]
 [   5  188 5161 ...    0    0    0]
 [  12  169    1 ...    0    0    0]
 ...
 [   3    1 3039 ...    0    0    0]
 [  26  172   27 ...    0    0    0]
 [   8    2 9571 ...    0    0    0]]


In [ ]:
# pipeline-1 -> Text Encoding
# model-1

model1 = Sequential()
model1.add(Embedding(vocab_size, 100,  weights=[embedding_matrix], input_length = 187, trainable=False))
# # model1.add(Flatten())
# layer_output = [layer.output for layer in model1.layers]
# print(model1.summary())
model1.add(Convolution1D(filters=256, kernel_size=(5), activation='relu'))
model1.add(Convolution1D(filters=128, kernel_size=(5), activation='relu'))
model1.add(Convolution1D(filters=64, kernel_size=(3), activation='relu'))
# print(layer_output)
# print(layer_output[0].get_shape().as_list())
model1.add(Bidirectional(LSTM(200)))
model1.add(Reshape((40,10)))
# model1.add(UpSampling2D())
# model1.add(UpSampling2D())

# opt = keras.optimizers.Adam(lr = 0.0001)
model1.compile(loss='mse',optimizer='adam',metrics=['acc'])
# summarize the model1
print(model1.summary())

# model1.fit(inp, output, batch_size=32, epochs=30)


Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 187, 100)          1413600   
_________________________________________________________________
conv1d_6 (Conv1D)            (None, 183, 256)          128256    
_________________________________________________________________
conv1d_7 (Conv1D)            (None, 179, 128)          163968    
_________________________________________________________________
conv1d_8 (Conv1D)            (None, 177, 64)           24640     
_________________________________________________________________
bidirectional_2 (Bidirection (None, 400)               424000    
_________________________________________________________________
reshape_2 (Reshape)          (None, 40, 10)            0         
Total params: 2,154,464
Trainable params: 740,864
Non-trainable params: 1,413,600
______________________________________

In [ ]:
!pip install keras-self-attention

  Created wheel for keras-self-attention: filename=keras_self_attention-0.49.0-cp37-none-any.whl size=19468 sha256=ecabbf2682d3b165aa304cfd7943698713d951f8ebffdc63e3c27cb7c8a990e7
  Stored in directory: /root/.cache/pip/wheels/6f/9d/c5/26693a5092d9313daeae94db04818fc0a2b7a48ea381989f34
Successfully built keras-self-attention


In [ ]:
# pipeline-2 -> user/speaker encoding
# model-2

model2 = Sequential()
# model2.add(keras.Input(shape=(128,128,3)))
# model2.add(Flatten())
# model2.add(keras.layers.Dense(128,activation='relu'))
# model2.add(keras.layers.Dense(256, activation='relu'))
# model2.add(keras.layers.Dense(128, activation='relu'))
model2.add(Convolution2D(32, 5 ,data_format = 'channels_last', padding = 'same', activation = 'relu', strides = 1, input_shape = (80, None, 1)))  
model2.add(AveragePooling2D(pool_size = (2, 2), padding = 'same'))  

model2.add(Convolution2D(64, 3, padding = 'same'))  
model2.add(AveragePooling2D(pool_size = (2, 2), padding = 'same'))  

layer_output = [layer.output for layer in model2.layers]
print(layer_output)
# print(layer_output[3].get_shape().as_list()[1:3])
# print(layer_output[0].get_shape().as_list()[1:3])
model2.add(Conv2DTranspose(24,(layer_output[3].get_shape().as_list()[1:3]),padding = 'same', activation = 'relu', strides = 2))
model2.add(Conv2DTranspose(3,(layer_output[0].get_shape().as_list()[1:3]),padding = 'same', activation = 'relu', strides = 2))

model2.compile(optimizer='adam', loss='mae', metrics=['accuracy'])
print(model2.summary())

model2.fit(orig, orig, epochs = 30)

[<KerasTensor: shape=(None, 80, None, 32) dtype=float32 (created by layer 'conv2d_3')>, <KerasTensor: shape=(None, 40, None, 32) dtype=float32 (created by layer 'average_pooling2d_2')>, <KerasTensor: shape=(None, 40, None, 64) dtype=float32 (created by layer 'conv2d_4')>, <KerasTensor: shape=(None, 20, None, 64) dtype=float32 (created by layer 'average_pooling2d_3')>]
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 80, None, 32)      832       
_________________________________________________________________
average_pooling2d_2 (Average (None, 40, None, 32)      0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 40, None, 64)      18496     
_________________________________________________________________
average_pooling2d_3 (Average (None, 20, None, 64)      0         
Total params:

In [ ]:
# merging two pipelines of models and preperation of final model

from keras.layers import *
from keras.models import Model

merged = Multiply()([model1.output, model2.output])
# print(mergedOut.shape)
# mergedNew = Conv2D(32, 5, padding = 'same', activation = 'relu', strides = 1)(mergedOut)
# print(mergedOut.shape)

# finalModel = Sequential()
# finalModel.add(combinedModel)
finalModel = Convolution2D(24, 5, padding = 'same', activation = 'relu', strides = 1)(merged)
finalModel = AveragePooling2D(pool_size = (2, 2), padding = 'same')(finalModel)

finalModel = Convolution2D(48, 3, padding = 'same')(finalModel)
finalModel = AveragePooling2D(pool_size = (2, 2), padding = 'same')(finalModel) 

finalModel = Convolution2D(64, 3, padding = 'same')(finalModel)
finalModel = AveragePooling2D(pool_size = (2, 2), padding = 'same')(finalModel) 
# layer_output = [layer.output for layer in finalModel.layers]
# print(layer_output)
# print(layer_output[3].get_shape().as_list()[1:3])
# print(layer_output[0].get_shape().as_list()[1:3])

finalModel = Conv2DTranspose(48,(finalModel.shape[1:3]),padding = 'same', activation = 'relu', strides = 2)(finalModel)
finalModel = Conv2DTranspose(24,(finalModel.shape[1:3]),padding = 'same', activation = 'relu', strides = 2)(finalModel)
finalModel = Conv2DTranspose(3,(finalModel.shape[1:3]),padding = 'same', activation = 'relu', strides = 2)(finalModel)

combinedModel = Model([model1.input,model2.input], finalModel)
combinedModel.compile(optimizer='adam', loss='mae', metrics=['accuracy'])

print(combinedModel.summary())

combinedModel.fit([inp, output], output, epochs = 30)

Model: "model_18"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
embedding_input (InputLayer)    [(None, 187)]        0                                            
__________________________________________________________________________________________________
embedding (Embedding)           (None, 187, 100)     1413600     embedding_input[0][0]            
__________________________________________________________________________________________________
conv1d (Conv1D)                 (None, 183, 256)     128256      embedding[0][0]                  
__________________________________________________________________________________________________
conv2d_52_input (InputLayer)    [(None, 128, 128, 3) 0                                            
___________________________________________________________________________________________

KeyboardInterrupt: ignored

In [ ]:
combinedModel.save('/content/gdrive/My Drive/Models/Temp-Model.h5')